version: "3.10"

services:
  jellyfin:
    image: "linuxserver/jellyfin:latest"
    restart: unless-stopped
    environment:
      PUID: 1000
      GUID: 1000
      TZ: "America/Sao_Paulo"
    ports:
      - 8096:8096
    volumes:
      - "/home/alcides/Videos:/multimedia:ro"
      - "jellyfin-config:/config"
      - "jellyfin-cache:/cache:"
    devices:
      - /dev/video10
      - /dev/video11
      - /dev/video12
      - /dev/video13
      - /dev/video14
      - /dev/video15
      - /dev/video16
      - /dev/video18
      - /dev/video19

volumes:
  jellyfin-config:
  jellyfin-cache: