version: "3.9"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: --no-autoupdate proxy-dns
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
      - "TUNNEL_DNS_ADDRESS=127.0.0.1"
      - "TUNNEL_DNS_PORT=5053"
    restart: unless-stopped
    network_mode: host
