version: "3.9"

services:
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - ./tailscale_var-lib:/var/lib
    environment:
      TS_HOSTNAME: hal001
      TS_USERSPACE: false
      TS_STATE_DIR: /var/lib/tailscale
      TS_AUTHKEY: ${AUTHKEY}
      TS_ROUTES: "192.168.0.0/24"
      TS_EXTRA_ARGS: "--advertise-exit-node --accept-routes --exit-node=${EXIT_NODE_IP} --exit-node-allow-lan-access=true"
    cap_add:
      - NET_RAW
      - NET_ADMIN
